# Defined by the ISO 3166 standard.  The ISO 3166 standard includes a
# "Country Subdivision Code", giving a code for the names of the principal
# administrative subdivisions of the countries coded in ISO 3166.
# 
# Data is based on http://svn.debian.org/wsvn/pkg-isocodes/trunk/iso-codes/iso_3166/iso_3166.xml?op=file
class Country < ActiveRecord::Base
  acts_as_enumeration
  
  column :official_name, :string
  column :alpha_2_code, :string
  column :alpha_3_code, :string
  
  has_many  :regions
  
  validates_presence_of   :alpha_2_code,
                          :alpha_3_code
  validates_length_of     :alpha_2_code,
                            :is => 2
  validates_length_of     :alpha_3_code,
                            :is => 3
  
  alias_attribute :abbreviation_2, :alpha_2_code
  alias_attribute :abbreviation_3, :alpha_3_code
  
  # The official name of the country
  def official_name
    self[:official_name] || name
  end
  
  create :id => 4, :name => "Afghanistan", :official_name => "Islamic Republic of Afghanistan", :alpha_2_code => 'AF', :alpha_3_code => 'AFG'
  create :id => 248, :name => "Åland Islands", :alpha_2_code => 'AX', :alpha_3_code => 'ALA'
  create :id => 8, :name => "Albania", :official_name => "Republic of Albania", :alpha_2_code => 'AL', :alpha_3_code => 'ALB'
  create :id => 12, :name => "Algeria", :official_name => "People's Democratic Republic of Algeria", :alpha_2_code => 'DZ', :alpha_3_code => 'DZA'
  create :id => 16, :name => "American Samoa", :alpha_2_code => 'AS', :alpha_3_code => 'ASM'
  create :id => 20, :name => "Andorra", :official_name => "Principality of Andorra", :alpha_2_code => 'AD', :alpha_3_code => 'AND'
  create :id => 24, :name => "Angola", :official_name => "Republic of Angola", :alpha_2_code => 'AO', :alpha_3_code => 'AGO'
  create :id => 660, :name => "Anguilla", :alpha_2_code => 'AI', :alpha_3_code => 'AIA'
  create :id => 10, :name => "Antarctica", :alpha_2_code => 'AQ', :alpha_3_code => 'ATA'
  create :id => 28, :name => "Antigua and Barbuda", :alpha_2_code => 'AG', :alpha_3_code => 'ATG'
  create :id => 32, :name => "Argentina", :official_name => "Argentine Republic", :alpha_2_code => 'AR', :alpha_3_code => 'ARG'
  create :id => 51, :name => "Armenia", :official_name => "Republic of Armenia", :alpha_2_code => 'AM', :alpha_3_code => 'ARM'
  create :id => 533, :name => "Aruba", :alpha_2_code => 'AW', :alpha_3_code => 'ABW'
  create :id => 36, :name => "Australia", :alpha_2_code => 'AU', :alpha_3_code => 'AUS'
  create :id => 40, :name => "Austria", :official_name => "Republic of Austria", :alpha_2_code => 'AT', :alpha_3_code => 'AUT'
  create :id => 31, :name => "Azerbaijan", :official_name => "Republic of Azerbaijan", :alpha_2_code => 'AZ', :alpha_3_code => 'AZE'
  create :id => 44, :name => "Bahamas", :official_name => "Commonwealth of the Bahamas", :alpha_2_code => 'BS', :alpha_3_code => 'BHS'
  create :id => 48, :name => "Bahrain", :official_name => "Kingdom of Bahrain", :alpha_2_code => 'BH', :alpha_3_code => 'BHR'
  create :id => 50, :name => "Bangladesh", :official_name => "People's Republic of Bangladesh", :alpha_2_code => 'BD', :alpha_3_code => 'BGD'
  create :id => 52, :name => "Barbados", :alpha_2_code => 'BB', :alpha_3_code => 'BRB'
  create :id => 112, :name => "Belarus", :official_name => "Republic of Belarus", :alpha_2_code => 'BY', :alpha_3_code => 'BLR'
  create :id => 56, :name => "Belgium", :official_name => "Kingdom of Belgium", :alpha_2_code => 'BE', :alpha_3_code => 'BEL'
  create :id => 84, :name => "Belize", :alpha_2_code => 'BZ', :alpha_3_code => 'BLZ'
  create :id => 204, :name => "Benin", :official_name => "Republic of Benin", :alpha_2_code => 'BJ', :alpha_3_code => 'BEN'
  create :id => 60, :name => "Bermuda", :alpha_2_code => 'BM', :alpha_3_code => 'BMU'
  create :id => 64, :name => "Bhutan", :official_name => "Kingdom of Bhutan", :alpha_2_code => 'BT', :alpha_3_code => 'BTN'
  create :id => 68, :name => "Bolivia", :official_name => "Republic of Bolivia", :alpha_2_code => 'BO', :alpha_3_code => 'BOL'
  create :id => 70, :name => "Bosnia and Herzegovina", :official_name => "Republic of Bosnia and Herzegovina", :alpha_2_code => 'BA', :alpha_3_code => 'BIH'
  create :id => 72, :name => "Botswana", :official_name => "Republic of Botswana", :alpha_2_code => 'BW', :alpha_3_code => 'BWA'
  create :id => 74, :name => "Bouvet Island", :alpha_2_code => 'BV', :alpha_3_code => 'BVT'
  create :id => 76, :name => "Brazil", :official_name => "Federative Republic of Brazil", :alpha_2_code => 'BR', :alpha_3_code => 'BRA'
  create :id => 86, :name => "British Indian Ocean Territory", :alpha_2_code => 'IO', :alpha_3_code => 'IOT'
  create :id => 96, :name => "Brunei Darussalam", :alpha_2_code => 'BN', :alpha_3_code => 'BRN'
  create :id => 100, :name => "Bulgaria", :official_name => "Republic of Bulgaria", :alpha_2_code => 'BG', :alpha_3_code => 'BGR'
  create :id => 854, :name => "Burkina Faso", :alpha_2_code => 'BF', :alpha_3_code => 'BFA'
  create :id => 108, :name => "Burundi", :official_name => "Republic of Burundi", :alpha_2_code => 'BI', :alpha_3_code => 'BDI'
  create :id => 116, :name => "Cambodia", :official_name => "Kingdom of Cambodia", :alpha_2_code => 'KH', :alpha_3_code => 'KHM'
  create :id => 120, :name => "Cameroon", :official_name => "Republic of Cameroon", :alpha_2_code => 'CM', :alpha_3_code => 'CMR'
  create :id => 124, :name => "Canada", :alpha_2_code => 'CA', :alpha_3_code => 'CAN'
  create :id => 132, :name => "Cape Verde", :official_name => "Republic of Cape Verde", :alpha_2_code => 'CV', :alpha_3_code => 'CPV'
  create :id => 136, :name => "Cayman Islands", :alpha_2_code => 'KY', :alpha_3_code => 'CYM'
  create :id => 140, :name => "Central African Republic", :alpha_2_code => 'CF', :alpha_3_code => 'CAF'
  create :id => 148, :name => "Chad", :official_name => "Republic of Chad", :alpha_2_code => 'TD', :alpha_3_code => 'TCD'
  create :id => 152, :name => "Chile", :official_name => "Republic of Chile", :alpha_2_code => 'CL', :alpha_3_code => 'CHL'
  create :id => 156, :name => "China", :official_name => "People's Republic of China", :alpha_2_code => 'CN', :alpha_3_code => 'CHN'
  create :id => 162, :name => "Christmas Island", :alpha_2_code => 'CX', :alpha_3_code => 'CXR'
  create :id => 166, :name => "Cocos (Keeling) Islands", :alpha_2_code => 'CC', :alpha_3_code => 'CCK'
  create :id => 170, :name => "Colombia", :official_name => "Republic of Colombia", :alpha_2_code => 'CO', :alpha_3_code => 'COL'
  create :id => 174, :name => "Comoros", :official_name => "Union of the Comoros", :alpha_2_code => 'KM', :alpha_3_code => 'COM'
  create :id => 178, :name => "Congo", :official_name => "Republic of the Congo", :alpha_2_code => 'CG', :alpha_3_code => 'COG'
  create :id => 180, :name => "Congo, The Democratic Republic of the", :alpha_2_code => 'CD', :alpha_3_code => 'COD'
  create :id => 184, :name => "Cook Islands", :alpha_2_code => 'CK', :alpha_3_code => 'COK'
  create :id => 188, :name => "Costa Rica", :official_name => "Republic of Costa Rica", :alpha_2_code => 'CR', :alpha_3_code => 'CRI'
  create :id => 384, :name => "Côte d'Ivoire", :official_name => "Republic of Côte d'Ivoire", :alpha_2_code => 'CI', :alpha_3_code => 'CIV'
  create :id => 191, :name => "Croatia", :official_name => "Republic of Croatia", :alpha_2_code => 'HR', :alpha_3_code => 'HRV'
  create :id => 192, :name => "Cuba", :official_name => "Republic of Cuba", :alpha_2_code => 'CU', :alpha_3_code => 'CUB'
  create :id => 196, :name => "Cyprus", :official_name => "Republic of Cyprus", :alpha_2_code => 'CY', :alpha_3_code => 'CYP'
  create :id => 203, :name => "Czech Republic", :alpha_2_code => 'CZ', :alpha_3_code => 'CZE'
  create :id => 208, :name => "Denmark", :official_name => "Kingdom of Denmark", :alpha_2_code => 'DK', :alpha_3_code => 'DNK'
  create :id => 262, :name => "Djibouti", :official_name => "Republic of Djibouti", :alpha_2_code => 'DJ', :alpha_3_code => 'DJI'
  create :id => 212, :name => "Dominica", :official_name => "Commonwealth of Dominica", :alpha_2_code => 'DM', :alpha_3_code => 'DMA'
  create :id => 214, :name => "Dominican Republic", :alpha_2_code => 'DO', :alpha_3_code => 'DOM'
  create :id => 218, :name => "Ecuador", :official_name => "Republic of Ecuador", :alpha_2_code => 'EC', :alpha_3_code => 'ECU'
  create :id => 818, :name => "Egypt", :official_name => "Arab Republic of Egypt", :alpha_2_code => 'EG', :alpha_3_code => 'EGY'
  create :id => 222, :name => "El Salvador", :official_name => "Republic of El Salvador", :alpha_2_code => 'SV', :alpha_3_code => 'SLV'
  create :id => 226, :name => "Equatorial Guinea", :official_name => "Republic of Equatorial Guinea", :alpha_2_code => 'GQ', :alpha_3_code => 'GNQ'
  create :id => 232, :name => "Eritrea", :alpha_2_code => 'ER', :alpha_3_code => 'ERI'
  create :id => 233, :name => "Estonia", :official_name => "Republic of Estonia", :alpha_2_code => 'EE', :alpha_3_code => 'EST'
  create :id => 231, :name => "Ethiopia", :official_name => "Federal Democratic Republic of Ethiopia", :alpha_2_code => 'ET', :alpha_3_code => 'ETH'
  create :id => 238, :name => "Falkland Islands (Malvinas)", :alpha_2_code => 'FK', :alpha_3_code => 'FLK'
  create :id => 234, :name => "Faroe Islands", :alpha_2_code => 'FO', :alpha_3_code => 'FRO'
  create :id => 242, :name => "Fiji", :official_name => "Republic of the Fiji Islands", :alpha_2_code => 'FJ', :alpha_3_code => 'FJI'
  create :id => 246, :name => "Finland", :official_name => "Republic of Finland", :alpha_2_code => 'FI', :alpha_3_code => 'FIN'
  create :id => 250, :name => "France", :official_name => "French Republic", :alpha_2_code => 'FR', :alpha_3_code => 'FRA'
  create :id => 254, :name => "French Guiana", :alpha_2_code => 'GF', :alpha_3_code => 'GUF'
  create :id => 258, :name => "French Polynesia", :alpha_2_code => 'PF', :alpha_3_code => 'PYF'
  create :id => 260, :name => "French Southern Territories", :alpha_2_code => 'TF', :alpha_3_code => 'ATF'
  create :id => 266, :name => "Gabon", :official_name => "Gabonese Republic", :alpha_2_code => 'GA', :alpha_3_code => 'GAB'
  create :id => 270, :name => "Gambia", :official_name => "Republic of the Gambia", :alpha_2_code => 'GM', :alpha_3_code => 'GMB'
  create :id => 268, :name => "Georgia", :alpha_2_code => 'GE', :alpha_3_code => 'GEO'
  create :id => 276, :name => "Germany", :official_name => "Federal Republic of Germany", :alpha_2_code => 'DE', :alpha_3_code => 'DEU'
  create :id => 288, :name => "Ghana", :official_name => "Republic of Ghana", :alpha_2_code => 'GH', :alpha_3_code => 'GHA'
  create :id => 292, :name => "Gibraltar", :alpha_2_code => 'GI', :alpha_3_code => 'GIB'
  create :id => 300, :name => "Greece", :official_name => "Hellenic Republic", :alpha_2_code => 'GR', :alpha_3_code => 'GRC'
  create :id => 304, :name => "Greenland", :alpha_2_code => 'GL', :alpha_3_code => 'GRL'
  create :id => 308, :name => "Grenada", :alpha_2_code => 'GD', :alpha_3_code => 'GRD'
  create :id => 312, :name => "Guadeloupe", :alpha_2_code => 'GP', :alpha_3_code => 'GLP'
  create :id => 316, :name => "Guam", :alpha_2_code => 'GU', :alpha_3_code => 'GUM'
  create :id => 320, :name => "Guatemala", :official_name => "Republic of Guatemala", :alpha_2_code => 'GT', :alpha_3_code => 'GTM'
  create :id => 831, :name => "Guernsey", :alpha_2_code => 'GG', :alpha_3_code => 'GGY'
  create :id => 324, :name => "Guinea", :official_name => "Republic of Guinea", :alpha_2_code => 'GN', :alpha_3_code => 'GIN'
  create :id => 624, :name => "Guinea-Bissau", :official_name => "Republic of Guinea-Bissau", :alpha_2_code => 'GW', :alpha_3_code => 'GNB'
  create :id => 328, :name => "Guyana", :official_name => "Republic of Guyana", :alpha_2_code => 'GY', :alpha_3_code => 'GUY'
  create :id => 332, :name => "Haiti", :official_name => "Republic of Haiti", :alpha_2_code => 'HT', :alpha_3_code => 'HTI'
  create :id => 334, :name => "Heard Island and McDonald Islands", :alpha_2_code => 'HM', :alpha_3_code => 'HMD'
  create :id => 336, :name => "Holy See (Vatican City State)", :alpha_2_code => 'VA', :alpha_3_code => 'VAT'
  create :id => 340, :name => "Honduras", :official_name => "Republic of Honduras", :alpha_2_code => 'HN', :alpha_3_code => 'HND'
  create :id => 344, :name => "Hong Kong", :official_name => "Hong Kong Special Administrative Region of China", :alpha_2_code => 'HK', :alpha_3_code => 'HKG'
  create :id => 348, :name => "Hungary", :official_name => "Republic of Hungary", :alpha_2_code => 'HU', :alpha_3_code => 'HUN'
  create :id => 352, :name => "Iceland", :official_name => "Republic of Iceland", :alpha_2_code => 'IS', :alpha_3_code => 'ISL'
  create :id => 356, :name => "India", :official_name => "Republic of India", :alpha_2_code => 'IN', :alpha_3_code => 'IND'
  create :id => 360, :name => "Indonesia", :official_name => "Republic of Indonesia", :alpha_2_code => 'ID', :alpha_3_code => 'IDN'
  create :id => 364, :name => "Iran, Islamic Republic of", :official_name => "Islamic Republic of Iran", :alpha_2_code => 'IR', :alpha_3_code => 'IRN'
  create :id => 368, :name => "Iraq", :official_name => "Republic of Iraq", :alpha_2_code => 'IQ', :alpha_3_code => 'IRQ'
  create :id => 372, :name => "Ireland", :alpha_2_code => 'IE', :alpha_3_code => 'IRL'
  create :id => 833, :name => "Isle of Man", :alpha_2_code => 'IM', :alpha_3_code => 'IMN'
  create :id => 376, :name => "Israel", :official_name => "State of Israel", :alpha_2_code => 'IL', :alpha_3_code => 'ISR'
  create :id => 380, :name => "Italy", :official_name => "Italian Republic", :alpha_2_code => 'IT', :alpha_3_code => 'ITA'
  create :id => 388, :name => "Jamaica", :alpha_2_code => 'JM', :alpha_3_code => 'JAM'
  create :id => 392, :name => "Japan", :alpha_2_code => 'JP', :alpha_3_code => 'JPN'
  create :id => 832, :name => "Jersey", :alpha_2_code => 'JE', :alpha_3_code => 'JEY'
  create :id => 400, :name => "Jordan", :official_name => "Hashemite Kingdom of Jordan", :alpha_2_code => 'JO', :alpha_3_code => 'JOR'
  create :id => 398, :name => "Kazakhstan", :official_name => "Republic of Kazakhstan", :alpha_2_code => 'KZ', :alpha_3_code => 'KAZ'
  create :id => 404, :name => "Kenya", :official_name => "Republic of Kenya", :alpha_2_code => 'KE', :alpha_3_code => 'KEN'
  create :id => 296, :name => "Kiribati", :official_name => "Republic of Kiribati", :alpha_2_code => 'KI', :alpha_3_code => 'KIR'
  create :id => 408, :name => "Korea, Democratic People's Republic of", :official_name => "Democratic People's Republic of Korea", :alpha_2_code => 'KP', :alpha_3_code => 'PRK'
  create :id => 410, :name => "Korea, Republic of", :alpha_2_code => 'KR', :alpha_3_code => 'KOR'
  create :id => 414, :name => "Kuwait", :official_name => "State of Kuwait", :alpha_2_code => 'KW', :alpha_3_code => 'KWT'
  create :id => 417, :name => "Kyrgyzstan", :official_name => "Kyrgyz Republic", :alpha_2_code => 'KG', :alpha_3_code => 'KGZ'
  create :id => 418, :name => "Lao People's Democratic Republic", :alpha_2_code => 'LA', :alpha_3_code => 'LAO'
  create :id => 428, :name => "Latvia", :official_name => "Republic of Latvia", :alpha_2_code => 'LV', :alpha_3_code => 'LVA'
  create :id => 422, :name => "Lebanon", :official_name => "Lebanese Republic", :alpha_2_code => 'LB', :alpha_3_code => 'LBN'
  create :id => 426, :name => "Lesotho", :official_name => "Kingdom of Lesotho", :alpha_2_code => 'LS', :alpha_3_code => 'LSO'
  create :id => 430, :name => "Liberia", :official_name => "Republic of Liberia", :alpha_2_code => 'LR', :alpha_3_code => 'LBR'
  create :id => 434, :name => "Libyan Arab Jamahiriya", :official_name => "Socialist People's Libyan Arab Jamahiriya", :alpha_2_code => 'LY', :alpha_3_code => 'LBY'
  create :id => 438, :name => "Liechtenstein", :official_name => "Principality of Liechtenstein", :alpha_2_code => 'LI', :alpha_3_code => 'LIE'
  create :id => 440, :name => "Lithuania", :official_name => "Republic of Lithuania", :alpha_2_code => 'LT', :alpha_3_code => 'LTU'
  create :id => 442, :name => "Luxembourg", :official_name => "Grand Duchy of Luxembourg", :alpha_2_code => 'LU', :alpha_3_code => 'LUX'
  create :id => 446, :name => "Macao", :official_name => "Macao Special Administrative Region of China", :alpha_2_code => 'MO', :alpha_3_code => 'MAC'
  create :id => 807, :name => "Macedonia, Republic of", :official_name => "The Former Yugoslav Republic of Macedonia", :alpha_2_code => 'MK', :alpha_3_code => 'MKD'
  create :id => 450, :name => "Madagascar", :official_name => "Republic of Madagascar", :alpha_2_code => 'MG', :alpha_3_code => 'MDG'
  create :id => 454, :name => "Malawi", :official_name => "Republic of Malawi", :alpha_2_code => 'MW', :alpha_3_code => 'MWI'
  create :id => 458, :name => "Malaysia", :alpha_2_code => 'MY', :alpha_3_code => 'MYS'
  create :id => 462, :name => "Maldives", :official_name => "Republic of Maldives", :alpha_2_code => 'MV', :alpha_3_code => 'MDV'
  create :id => 466, :name => "Mali", :official_name => "Republic of Mali", :alpha_2_code => 'ML', :alpha_3_code => 'MLI'
  create :id => 470, :name => "Malta", :official_name => "Republic of Malta", :alpha_2_code => 'MT', :alpha_3_code => 'MLT'
  create :id => 584, :name => "Marshall Islands", :official_name => "Republic of the Marshall Islands", :alpha_2_code => 'MH', :alpha_3_code => 'MHL'
  create :id => 474, :name => "Martinique", :alpha_2_code => 'MQ', :alpha_3_code => 'MTQ'
  create :id => 478, :name => "Mauritania", :official_name => "Islamic Republic of Mauritania", :alpha_2_code => 'MR', :alpha_3_code => 'MRT'
  create :id => 480, :name => "Mauritius", :official_name => "Republic of Mauritius", :alpha_2_code => 'MU', :alpha_3_code => 'MUS'
  create :id => 175, :name => "Mayotte", :alpha_2_code => 'YT', :alpha_3_code => 'MYT'
  create :id => 484, :name => "Mexico", :official_name => "United Mexican States", :alpha_2_code => 'MX', :alpha_3_code => 'MEX'
  create :id => 583, :name => "Micronesia, Federated States of", :official_name => "Federated States of Micronesia", :alpha_2_code => 'FM', :alpha_3_code => 'FSM'
  create :id => 498, :name => "Moldova, Republic of", :official_name => "Republic of Moldova", :alpha_2_code => 'MD', :alpha_3_code => 'MDA'
  create :id => 492, :name => "Monaco", :official_name => "Principality of Monaco", :alpha_2_code => 'MC', :alpha_3_code => 'MCO'
  create :id => 496, :name => "Mongolia", :alpha_2_code => 'MN', :alpha_3_code => 'MNG'
  create :id => 499, :name => "Montenegro", :official_name => "Republic of Montenegro", :alpha_2_code => 'ME', :alpha_3_code => 'MNE'
  create :id => 500, :name => "Montserrat", :alpha_2_code => 'MS', :alpha_3_code => 'MSR'
  create :id => 504, :name => "Morocco", :official_name => "Kingdom of Morocco", :alpha_2_code => 'MA', :alpha_3_code => 'MAR'
  create :id => 508, :name => "Mozambique", :official_name => "Republic of Mozambique", :alpha_2_code => 'MZ', :alpha_3_code => 'MOZ'
  create :id => 104, :name => "Myanmar", :official_name => "Union of Myanmar", :alpha_2_code => 'MM', :alpha_3_code => 'MMR'
  create :id => 516, :name => "Namibia", :official_name => "Republic of Namibia", :alpha_2_code => 'NA', :alpha_3_code => 'NAM'
  create :id => 520, :name => "Nauru", :official_name => "Republic of Nauru", :alpha_2_code => 'NR', :alpha_3_code => 'NRU'
  create :id => 524, :name => "Nepal", :official_name => "Kingdom of Nepal", :alpha_2_code => 'NP', :alpha_3_code => 'NPL'
  create :id => 528, :name => "Netherlands", :official_name => "Kingdom of the Netherlands", :alpha_2_code => 'NL', :alpha_3_code => 'NLD'
  create :id => 530, :name => "Netherlands Antilles", :alpha_2_code => 'AN', :alpha_3_code => 'ANT'
  create :id => 540, :name => "New Caledonia", :alpha_2_code => 'NC', :alpha_3_code => 'NCL'
  create :id => 554, :name => "New Zealand", :alpha_2_code => 'NZ', :alpha_3_code => 'NZL'
  create :id => 558, :name => "Nicaragua", :official_name => "Republic of Nicaragua", :alpha_2_code => 'NI', :alpha_3_code => 'NIC'
  create :id => 562, :name => "Niger", :official_name => "Republic of the Niger", :alpha_2_code => 'NE', :alpha_3_code => 'NER'
  create :id => 566, :name => "Nigeria", :official_name => "Federal Republic of Nigeria", :alpha_2_code => 'NG', :alpha_3_code => 'NGA'
  create :id => 570, :name => "Niue", :official_name => "Republic of Niue", :alpha_2_code => 'NU', :alpha_3_code => 'NIU'
  create :id => 574, :name => "Norfolk Island", :alpha_2_code => 'NF', :alpha_3_code => 'NFK'
  create :id => 580, :name => "Northern Mariana Islands", :official_name => "Commonwealth of the Northern Mariana Islands", :alpha_2_code => 'MP', :alpha_3_code => 'MNP'
  create :id => 578, :name => "Norway", :official_name => "Kingdom of Norway", :alpha_2_code => 'NO', :alpha_3_code => 'NOR'
  create :id => 512, :name => "Oman", :official_name => "Sultanate of Oman", :alpha_2_code => 'OM', :alpha_3_code => 'OMN'
  create :id => 586, :name => "Pakistan", :official_name => "Islamic Republic of Pakistan", :alpha_2_code => 'PK', :alpha_3_code => 'PAK'
  create :id => 585, :name => "Palau", :official_name => "Republic of Palau", :alpha_2_code => 'PW', :alpha_3_code => 'PLW'
  create :id => 275, :name => "Palestinian Territory, Occupied", :official_name => "Occupied Palestinian Territory", :alpha_2_code => 'PS', :alpha_3_code => 'PSE'
  create :id => 591, :name => "Panama", :official_name => "Republic of Panama", :alpha_2_code => 'PA', :alpha_3_code => 'PAN'
  create :id => 598, :name => "Papua New Guinea", :alpha_2_code => 'PG', :alpha_3_code => 'PNG'
  create :id => 600, :name => "Paraguay", :official_name => "Republic of Paraguay", :alpha_2_code => 'PY', :alpha_3_code => 'PRY'
  create :id => 604, :name => "Peru", :official_name => "Republic of Peru", :alpha_2_code => 'PE', :alpha_3_code => 'PER'
  create :id => 608, :name => "Philippines", :official_name => "Republic of the Philippines", :alpha_2_code => 'PH', :alpha_3_code => 'PHL'
  create :id => 612, :name => "Pitcairn", :alpha_2_code => 'PN', :alpha_3_code => 'PCN'
  create :id => 616, :name => "Poland", :official_name => "Republic of Poland", :alpha_2_code => 'PL', :alpha_3_code => 'POL'
  create :id => 620, :name => "Portugal", :official_name => "Portuguese Republic", :alpha_2_code => 'PT', :alpha_3_code => 'PRT'
  create :id => 630, :name => "Puerto Rico", :alpha_2_code => 'PR', :alpha_3_code => 'PRI'
  create :id => 634, :name => "Qatar", :official_name => "State of Qatar", :alpha_2_code => 'QA', :alpha_3_code => 'QAT'
  create :id => 638, :name => "Reunion", :alpha_2_code => 'RE', :alpha_3_code => 'REU'
  create :id => 642, :name => "Romania", :alpha_2_code => 'RO', :alpha_3_code => 'ROU'
  create :id => 643, :name => "Russian Federation", :alpha_2_code => 'RU', :alpha_3_code => 'RUS'
  create :id => 646, :name => "Rwanda", :official_name => "Rwandese Republic", :alpha_2_code => 'RW', :alpha_3_code => 'RWA'
  create :id => 652, :name => "Saint Barthélemy", :alpha_2_code => 'BL', :alpha_3_code => 'BLM'
  create :id => 654, :name => "Saint Helena", :alpha_2_code => 'SH', :alpha_3_code => 'SHN'
  create :id => 659, :name => "Saint Kitts and Nevis", :alpha_2_code => 'KN', :alpha_3_code => 'KNA'
  create :id => 662, :name => "Saint Lucia", :alpha_2_code => 'LC', :alpha_3_code => 'LCA'
  create :id => 663, :name => "Saint Martin (French part)", :alpha_2_code => 'MF', :alpha_3_code => 'MAF'
  create :id => 666, :name => "Saint Pierre and Miquelon", :alpha_2_code => 'PM', :alpha_3_code => 'SPM'
  create :id => 670, :name => "Saint Vincent and the Grenadines", :alpha_2_code => 'VC', :alpha_3_code => 'VCT'
  create :id => 882, :name => "Samoa", :official_name => "Independent State of Samoa", :alpha_2_code => 'WS', :alpha_3_code => 'WSM'
  create :id => 674, :name => "San Marino", :official_name => "Republic of San Marino", :alpha_2_code => 'SM', :alpha_3_code => 'SMR'
  create :id => 678, :name => "Sao Tome and Principe", :official_name => "Democratic Republic of Sao Tome and Principe", :alpha_2_code => 'ST', :alpha_3_code => 'STP'
  create :id => 682, :name => "Saudi Arabia", :official_name => "Kingdom of Saudi Arabia", :alpha_2_code => 'SA', :alpha_3_code => 'SAU'
  create :id => 686, :name => "Senegal", :official_name => "Republic of Senegal", :alpha_2_code => 'SN', :alpha_3_code => 'SEN'
  create :id => 688, :name => "Serbia", :official_name => "Republic of Serbia", :alpha_2_code => 'RS', :alpha_3_code => 'SRB'
  create :id => 690, :name => "Seychelles", :official_name => "Republic of Seychelles", :alpha_2_code => 'SC', :alpha_3_code => 'SYC'
  create :id => 694, :name => "Sierra Leone", :official_name => "Republic of Sierra Leone", :alpha_2_code => 'SL', :alpha_3_code => 'SLE'
  create :id => 702, :name => "Singapore", :official_name => "Republic of Singapore", :alpha_2_code => 'SG', :alpha_3_code => 'SGP'
  create :id => 703, :name => "Slovakia", :official_name => "Slovak Republic", :alpha_2_code => 'SK', :alpha_3_code => 'SVK'
  create :id => 705, :name => "Slovenia", :official_name => "Republic of Slovenia", :alpha_2_code => 'SI', :alpha_3_code => 'SVN'
  create :id => 90, :name => "Solomon Islands", :alpha_2_code => 'SB', :alpha_3_code => 'SLB'
  create :id => 706, :name => "Somalia", :official_name => "Somali Republic", :alpha_2_code => 'SO', :alpha_3_code => 'SOM'
  create :id => 710, :name => "South Africa", :official_name => "Republic of South Africa", :alpha_2_code => 'ZA', :alpha_3_code => 'ZAF'
  create :id => 239, :name => "South Georgia and the South Sandwich Islands", :alpha_2_code => 'GS', :alpha_3_code => 'SGS'
  create :id => 724, :name => "Spain", :official_name => "Kingdom of Spain", :alpha_2_code => 'ES', :alpha_3_code => 'ESP'
  create :id => 144, :name => "Sri Lanka", :official_name => "Democratic Socialist Republic of Sri Lanka", :alpha_2_code => 'LK', :alpha_3_code => 'LKA'
  create :id => 736, :name => "Sudan", :official_name => "Republic of the Sudan", :alpha_2_code => 'SD', :alpha_3_code => 'SDN'
  create :id => 740, :name => "Suriname", :official_name => "Republic of Suriname", :alpha_2_code => 'SR', :alpha_3_code => 'SUR'
  create :id => 744, :name => "Svalbard and Jan Mayen", :alpha_2_code => 'SJ', :alpha_3_code => 'SJM'
  create :id => 748, :name => "Swaziland", :official_name => "Kingdom of Swaziland", :alpha_2_code => 'SZ', :alpha_3_code => 'SWZ'
  create :id => 752, :name => "Sweden", :official_name => "Kingdom of Sweden", :alpha_2_code => 'SE', :alpha_3_code => 'SWE'
  create :id => 756, :name => "Switzerland", :official_name => "Swiss Confederation", :alpha_2_code => 'CH', :alpha_3_code => 'CHE'
  create :id => 760, :name => "Syrian Arab Republic", :alpha_2_code => 'SY', :alpha_3_code => 'SYR'
  create :id => 158, :name => "Taiwan, Province of China", :official_name => "Taiwan, Province of China", :alpha_2_code => 'TW', :alpha_3_code => 'TWN'
  create :id => 762, :name => "Tajikistan", :official_name => "Republic of Tajikistan", :alpha_2_code => 'TJ', :alpha_3_code => 'TJK'
  create :id => 834, :name => "Tanzania, United Republic of", :official_name => "United Republic of Tanzania", :alpha_2_code => 'TZ', :alpha_3_code => 'TZA'
  create :id => 764, :name => "Thailand", :official_name => "Kingdom of Thailand", :alpha_2_code => 'TH', :alpha_3_code => 'THA'
  create :id => 626, :name => "Timor-Leste", :official_name => "Democratic Republic of Timor-Leste", :alpha_2_code => 'TL', :alpha_3_code => 'TLS'
  create :id => 768, :name => "Togo", :official_name => "Togolese Republic", :alpha_2_code => 'TG', :alpha_3_code => 'TGO'
  create :id => 772, :name => "Tokelau", :alpha_2_code => 'TK', :alpha_3_code => 'TKL'
  create :id => 776, :name => "Tonga", :official_name => "Kingdom of Tonga", :alpha_2_code => 'TO', :alpha_3_code => 'TON'
  create :id => 780, :name => "Trinidad and Tobago", :official_name => "Republic of Trinidad and Tobago", :alpha_2_code => 'TT', :alpha_3_code => 'TTO'
  create :id => 788, :name => "Tunisia", :official_name => "Republic of Tunisia", :alpha_2_code => 'TN', :alpha_3_code => 'TUN'
  create :id => 792, :name => "Turkey", :official_name => "Republic of Turkey", :alpha_2_code => 'TR', :alpha_3_code => 'TUR'
  create :id => 795, :name => "Turkmenistan", :alpha_2_code => 'TM', :alpha_3_code => 'TKM'
  create :id => 796, :name => "Turks and Caicos Islands", :alpha_2_code => 'TC', :alpha_3_code => 'TCA'
  create :id => 798, :name => "Tuvalu", :alpha_2_code => 'TV', :alpha_3_code => 'TUV'
  create :id => 800, :name => "Uganda", :official_name => "Republic of Uganda", :alpha_2_code => 'UG', :alpha_3_code => 'UGA'
  create :id => 804, :name => "Ukraine", :alpha_2_code => 'UA', :alpha_3_code => 'UKR'
  create :id => 784, :name => "United Arab Emirates", :alpha_2_code => 'AE', :alpha_3_code => 'ARE'
  create :id => 826, :name => "United Kingdom", :official_name => "United Kingdom of Great Britain and Northern Ireland", :alpha_2_code => 'GB', :alpha_3_code => 'GBR'
  create :id => 840, :name => "United States", :official_name => "United States of America", :alpha_2_code => 'US', :alpha_3_code => 'USA'
  create :id => 581, :name => "United States Minor Outlying Islands", :alpha_2_code => 'UM', :alpha_3_code => 'UMI'
  create :id => 858, :name => "Uruguay", :official_name => "Eastern Republic of Uruguay", :alpha_2_code => 'UY', :alpha_3_code => 'URY'
  create :id => 860, :name => "Uzbekistan", :official_name => "Republic of Uzbekistan", :alpha_2_code => 'UZ', :alpha_3_code => 'UZB'
  create :id => 548, :name => "Vanuatu", :official_name => "Republic of Vanuatu", :alpha_2_code => 'VU', :alpha_3_code => 'VUT'
  create :id => 862, :name => "Venezuela", :official_name => "Bolivarian Republic of Venezuela", :alpha_2_code => 'VE', :alpha_3_code => 'VEN'
  create :id => 704, :name => "Viet Nam", :official_name => "Socialist Republic of Viet Nam", :alpha_2_code => 'VN', :alpha_3_code => 'VNM'
  create :id => 92, :name => "Virgin Islands, British", :official_name => "British Virgin Islands", :alpha_2_code => 'VG', :alpha_3_code => 'VGB'
  create :id => 850, :name => "Virgin Islands, U.S.", :official_name => "Virgin Islands of the United States", :alpha_2_code => 'VI', :alpha_3_code => 'VIR'
  create :id => 876, :name => "Wallis and Futuna", :alpha_2_code => 'WF', :alpha_3_code => 'WLF'
  create :id => 732, :name => "Western Sahara", :alpha_2_code => 'EH', :alpha_3_code => 'ESH'
  create :id => 887, :name => "Yemen", :official_name => "Republic of Yemen", :alpha_2_code => 'YE', :alpha_3_code => 'YEM'
  create :id => 894, :name => "Zambia", :official_name => "Republic of Zambia", :alpha_2_code => 'ZM', :alpha_3_code => 'ZMB'
  create :id => 716, :name => "Zimbabwe", :official_name => "Republic of Zimbabwe", :alpha_2_code => 'ZW', :alpha_3_code => 'ZWE'
end
